# Generated by Django 5.2.7 on 2026-01-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('PHYSIO', 'Physiotherapist'), ('RECEPTIONIST', 'Receptionist'), ('PATIENT', 'Patient')], db_index=True, default='PATIENT', max_length=50),
        ),
    ]
