# Generated by Django 5.2.7 on 2025-12-20 22:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('tax_id', models.CharField(max_length=50, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True)),
                ('insurance_provider', models.CharField(blank=True, help_text='Insurance company name', max_length=100)),
                ('insurance_policy_number', models.CharField(blank=True, max_length=100)),
                ('medical_history', models.TextField(blank=True, help_text='Past surgeries, chronic conditions, etc.')),
                ('allergies', models.TextField(blank=True, help_text='List of known allergies')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck if patient is archived')),
                ('distance_from_clinic', models.FloatField(default=5.0, help_text='Distance in KM')),
                ('no_show_history', models.IntegerField(default=0, help_text='Number of past missed appointments')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
